# Generated by Django 2.0 on 2018-03-28 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='level',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'High school'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], default='MASTER', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
