# Generated by Django 2.0 on 2018-03-28 21:10

from django.db import migrations
from django.contrib.gis.geos import Point


def populate_location(apps, schema_editor):
    Location = apps.get_model('accounts', 'Location')

    for location in Location.objects.all():
        location.location = Point(location.longitude, location.latitude, srid=4326)
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location_location'),
    ]

    operations = [
        migrations.RunPython(populate_location, migrations.RunPython.noop)
    ]
