# Generated by Django 2.0 on 2018-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180328_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locations',
            field=models.ManyToManyField(related_name='students', to='accounts.Location'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='locations',
            field=models.ManyToManyField(related_name='tutors', to='accounts.Location'),
        ),
    ]
