# Generated by Django 2.0 on 2018-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180319_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
