# Generated by Django 2.0 on 2018-04-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180328_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='location',
            name='google_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
