# Generated by Django 2.0 on 2018-04-13 09:19

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180402_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subjects',
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=2), default=list, size=None),
        ),
    ]
