# Generated by Django 2.0 on 2018-03-20 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('tutor_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('student_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('student_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.Location')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
            ],
        ),
    ]
